/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package customMiniRetrieve;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class MiniRetrieve {
    private static final String DOCUMENT_PATH = "documents/";
    private static final String QUERRY_PATH = "queries/";

    private static Map<Integer, File> querries;
    private static Map<Integer, File> documents;
    //word (fname->freq)
    private static Map<String, Map<File, Integer>> invIndex;
    private static Map<File, String> nonInvIndex;


    public static void main(String[] args) {
        querries = readDirectory(QUERRY_PATH);
        documents = readDirectory(DOCUMENT_PATH);
        invIndex = new HashMap<>();
        //System.out.println(tokenizeString(querries.get(1)));
        indexing(querries,documents);

    }
    //todo dont save documents as a string in hashmap
    private static void indexing(Map<Integer, File> querries, Map<Integer, File> documents) {
        for (File doc : documents.values()) {
            List<String> terms = tokenizeString(readFile(doc));
            for (String term : terms) {
                //if invIndex already contains word and a doc already containing that term once increment
                if (invIndex.containsKey(term) && invIndex.get(term).containsKey(doc)) {
                    Map<File, Integer> mapOfTerm = invIndex.get(term);
                    mapOfTerm.put(doc, (mapOfTerm.get(doc) + 1));
                // if invIndex contains word already but not with this doc put doc with count 1
                } else if (invIndex.containsKey(term)) {
                    invIndex.get(term).put(doc, 1);
                // if term is new in invIndex put it there with the doc it was found
                } else {
                    Map<File,Integer> newMap = new HashMap<>();
                    newMap.put(doc, 1);
                    invIndex.put(term, newMap);
                }
            }
        }
        System.out.println(invIndex);
    }

    private static List<String> tokenizeString(String fullString) {
        List<String> rawTokens = Arrays.asList(fullString.split(" "));
        List<String> trimmedTokens = rawTokens.stream().map(String::trim).collect(Collectors.toList());
        List<String> cleanedTokens = trimmedTokens.stream().map(s -> s.replace("\\.\\,\\;\\<\\>\\/\\?\\!\\(\\)\\[\\]\\{\\}", "")).collect(Collectors.toList());
        List<String> lowercasedToken = cleanedTokens.stream().map(String::toLowerCase).collect(Collectors.toList());
        return lowercasedToken;
    }

    private static String readFile(File file) {
            String output = "";
            try (BufferedReader bf = new BufferedReader(new FileReader(file))) {
                String line = null;
                StringBuilder sb = new StringBuilder();
                while ((line = bf.readLine()) != null) {
                    sb.append(line);
                }
                output = sb.toString();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        return output;
    }

    private static Map<Integer, File> readDirectory(String path) {
        HashMap<Integer, File> map = new HashMap<>();
        try (Stream<Path> paths = Files.walk(Paths.get(path))) {
            paths
                    .filter(Files::isRegularFile)
                    .forEach(e -> map.put(Integer.valueOf(e.toFile().getName()), e.toFile()));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return map;
    }
}
