/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package customMiniRetrieve;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    //we don't do that here
}
